apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-habucijm
  janus-idp.io/tekton: go-habucijm
  backstage.io/kubernetes-id: go-habucijm
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: go-habucijm
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
